from .link_prediction import perform_link_prediction_single
from .influence_maximization import perform_influence_maximization_single
from .node_classification import perform_node_classification_single